import argparse
import json
import zipfile
import urllib.request
import shutil
import os
import glob
import textwrap

parser = argparse.ArgumentParser(description="typst-fontawesome helper script")

parser.add_argument(
    "-d",
    "--download",
    help="Download FontAwesome fonts and metadata (occur two times to extract the zip file)",
    action="count",
    default=0,
)
parser.add_argument("-v", "--version", help="FontAwesome version", required=True)
parser.add_argument(
    "-o", "--output", help="Output dir (default: current dir .)", default="."
)
parser.add_argument(
    "-g",
    "--generate",
    help="Generate typst files (can be `lib`, `doc`)",
    default=["lib", "doc"],
)


def download(version, output, extract=False):
    ZIP_LINK_TEMPLATE = (
        "https://use.fontawesome.com/releases/v{}/fontawesome-free-{}-desktop.zip"
    )
    zip_link = ZIP_LINK_TEMPLATE.format(version, version)

    print(f"Downloading FontAwesome {version} metadata from {zip_link}")

    zip_file = os.path.join(output, "fontawesome.zip")

    # Download the zip file to the output directory
    req = urllib.request.Request(zip_link, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req) as response:
        with open(zip_file, "wb") as f:
            shutil.copyfileobj(response, f)

    if extract:
        with zipfile.ZipFile(zip_file, "r") as zip_ref:
            zip_ref.extractall(output)


def generate_lib(version, output):
    print(f"Generating typst lib for FontAwesome {version}")

    LIB_PREAMBLE_TEMPLATE = """\
    /*

    typst-fontawesome

    https://github.com/duskmoon314/typst-fontawesome

    generated by typst-fontawesome helper python script

    */

    #let FA_VERSION = state("fa-version", "Font Awesome {major_version}")
    #let FA_SET = state("fa-set", "Free")

    #let fa-icon(
      name,
      fa-version: FA_VERSION,
      fa-set: FA_SET,
      ..args
    ) = {{
      locate(loc => {{
        let fa-version = if type(fa-version) == "string" {{
          fa-version
        }} else {{
          fa-version.at(loc)
        }}
        let fa-set = if type(fa-set) == "string" {{
          fa-set
        }} else {{
          fa-set.at(loc)
        }}

        text(
          font: fa-version + " " + fa-set,
          name,
          ..args
        )
      }})
    }}

    """

    # split the version to get the major version
    major_version = version.split(".")[0]

    lib_preamble = textwrap.dedent(LIB_PREAMBLE_TEMPLATE).format(
        major_version=major_version
    )

    lib_file = os.path.join(output, "lib.typ")

    with open(lib_file, "w") as f:
        f.write(lib_preamble)

        # Find the metadata/icons.json file with glob
        icons_file = glob.glob(
            os.path.join(output, "**/metadata/icons.json"), recursive=True
        )
        if len(icons_file) == 0:
            raise Exception("Cannot find metadata/icons.json")
        icons_file = icons_file[0]

        with open(icons_file, "r") as icons_f:
            icons_data = json.load(icons_f)

            for icon_name, icon_data in icons_data.items():
                # Generate the icon line
                f.write(
                    f"#let fa-{icon_name} = fa-icon.with(\"\\u{{{icon_data['unicode']}}}\")\n"
                )

                # Generate the alias lines
                if "aliases" in icon_data:
                    if "names" in icon_data["aliases"]:
                        for alias_name in icon_data["aliases"]["names"]:
                            f.write(
                                f"#let fa-{alias_name} = fa-icon.with(\"\\u{{{icon_data['unicode']}}}\")\n"
                            )


def generate_doc(version, output):
    print(f"Generating typst doc for FontAwesome {version}")

    DOC_TEMPLATE = """\
    #import "lib.typ": *

    = typst-fontawesome

    duskmoon314

    https://github.com/duskmoon314/typst-fontawesome

    A Typst library for Font Awesome {version} icons through the desktop fonts.

    == Usage

    === Install the fonts

    You can download the fonts from the official website: https://fontawesome.com/download

    Or you can use the helper script to download the fonts and metadata:

    `python helper.py -dd -v {version}`

    Here `-dd` means download and extract the zip file. You can use `-d` to only download the zip file.

    After downloading the zip file, you can install the fonts depending on your OS.

    ==== Typst web app

    You can simply upload the `otf` files to the web app and use them with this package.

    ==== Mac

    You can double click the `otf` files to install them.

    === Import the library

    ==== Using the typst packages

    You can install the library using the typst packages:

    `#import "@preview/fontawesome:0.1.0": *`

    ==== Manually install

    Put the `lib.typ` file in your project directory, and import it:

    `#import "lib.typ": *`

    Here I recommend renaming the `lib.typ` file to `fontawesome.typ` to avoid name conflicts.

    === Use the icons

    You can use the `fa-icon` function to create an icon with its name:

    `fa-icon("chess-queen")` #fa-icon("chess-queen")

    Or you can use the `fa-` prefix to create an icon with its name:

    `fa-chess-queen()` #fa-chess-queen()

    ==== Different sets

    By default, the library uses the free set. You can change it by passing the `fa-set` parameter to `fa-icon`:

    `#fa-icon("github", fa-set: "Brands")` #fa-icon("github", fa-set: "Brands")

    Or you can change the default set by changing the `FA_SET` state. Let's try with the github icon:

    `#fa-icon("github")` #fa-icon("github")

    `FA_SET.update("Brands")` #FA_SET.update("Brands")

    `#fa-icon("github")` #fa-icon("github")

    Reset the default set:

    `FA_SET.update("Free")` #FA_SET.update("Free")

    ==== Customization

    The `fa-icon` function passes args to `text`, so you can customize the icon by passing parameters to it:

    `#fa-icon("chess-queen", fill: blue)` #fa-icon("chess-queen", fill: blue)

    `#fa-chess-queen(size: 15pt)` #fa-chess-queen(size: 15pt)

    == Gallery

    """

    doc_file = os.path.join(output, "example.typ")

    with open(doc_file, "w") as f:
        f.write(textwrap.dedent(DOC_TEMPLATE).format(version=version))

        # Find the metadata/icons.json file with glob
        icons_file = glob.glob(
            os.path.join(output, "**/metadata/icons.json"), recursive=True
        )
        if len(icons_file) == 0:
            raise Exception("Cannot find metadata/icons.json")
        icons_file = icons_file[0]

        with open(icons_file, "r") as icons_f:
            icons_data = json.load(icons_f)

            for icon_name, icon_data in icons_data.items():
                # Generate the icon line
                f.write(
                    f"#grid(columns: (20em, 10em, 3em), `#fa-{icon_name}()`, fa-{icon_name}())\n"
                )

                # Generate the alias lines
                if "aliases" in icon_data:
                    if "names" in icon_data["aliases"]:
                        for alias_name in icon_data["aliases"]["names"]:
                            f.write(
                                f"#grid(columns: (20em, 10em, 3em), `#fa-{alias_name}()`, fa-{alias_name}())\n"
                            )


def main():
    args = parser.parse_args()

    if args.download > 0:
        download(args.version, args.output, args.download > 1)

    if "lib" in args.generate:
        generate_lib(args.version, args.output)

    if "doc" in args.generate:
        generate_doc(args.version, args.output)


if __name__ == "__main__":
    main()
